name: ac3r
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.2=py39hecd8cb5_1001
  - argon2-cffi=20.1.0=py39h9ed2024_1
  - async_generator=1.10=pyhd3eb1b0_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=3.3.0=pyhd3eb1b0_0
  - ca-certificates=2021.5.25=hecd8cb5_1
  - certifi=2021.5.30=py39hecd8cb5_0
  - cffi=1.14.5=py39h2125817_0
  - click=7.1.2=py_0
  - cycler=0.10.0=py_2
  - decorator=5.0.9=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - descartes=1.1.0=py_4
  - entrypoints=0.3=py39hecd8cb5_0
  - freetype=2.10.4=ha233b18_0
  - geos=3.8.1=h4a8c4bd_0
  - icu=58.2=h0a44026_3
  - importlib-metadata=3.10.0=py39hecd8cb5_0
  - importlib_metadata=3.10.0=hd3eb1b0_0
  - intel-openmp=2019.4=233
  - ipykernel=5.3.4=py39h01d92e1_0
  - ipython=7.22.0=py39h01d92e1_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.3=pyhd3eb1b0_1
  - jedi=0.17.2=py39hecd8cb5_1
  - jpeg=9b=he5867d9_2
  - jsonschema=3.2.0=py_2
  - jupyter=1.0.0=py39hecd8cb5_7
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_console=6.4.0=pyhd3eb1b0_0
  - jupyter_core=4.7.1=py39hecd8cb5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - kiwisolver=1.3.1=py39hedf5dff_1
  - lcms2=2.11=h92f6f08_0
  - libcxx=11.0.1=habf9029_0
  - libedit=3.1.20191231=h1de35cc_1
  - libffi=3.3=hb1e8313_2
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.18=h1de35cc_0
  - libtiff=4.1.0=hcb84e12_1
  - lz4-c=1.9.2=h79c402e_3
  - matplotlib=3.3.2=hecd8cb5_0
  - matplotlib-base=3.3.2=py39h5039afe_1
  - mistune=0.8.4=py39h9ed2024_1000
  - mkl=2019.4=233
  - mkl-service=2.3.0=py39h9ed2024_0
  - mkl_fft=1.0.6=py39h16bde0e_0
  - mkl_random=1.0.2=py39h16bde0e_0
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.0.7=py39hecd8cb5_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.2=h0a44026_1
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - notebook=6.4.0=py39hecd8cb5_0
  - numpy=1.19.2=py39he57783f_0
  - numpy-base=1.19.2=py39hde55871_0
  - olefile=0.46=py_0
  - openssl=1.1.1k=h9ed2024_0
  - packaging=20.9=pyhd3eb1b0_0
  - pandas=1.2.3=py39hb2f4e1b_0
  - pandoc=2.12=hecd8cb5_0
  - pandocfilters=1.4.3=py39hecd8cb5_1
  - parso=0.7.0=py_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.1.0=py39h5270095_0
  - pip=21.1.2=py39hecd8cb5_0
  - prometheus_client=0.10.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.17=pyh06a4308_0
  - prompt_toolkit=3.0.17=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.20=py_2
  - pygments=2.9.0=pyhd3eb1b0_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py39h23ab428_6
  - pyrsistent=0.17.3=py39h9ed2024_0
  - python=3.9.0=h4f09611_5_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.9=1_cp39
  - pytz=2021.1=pyhd3eb1b0_0
  - pyzmq=20.0.0=py39h23ab428_1
  - qt=5.9.7=h468cd18_1
  - qtconsole=5.0.3=pyhd3eb1b0_0
  - qtpy=1.9.0=py_0
  - readline=8.0=h1de35cc_0
  - scipy=1.5.2=py39h2515648_0
  - seaborn=0.11.1=pyhd3eb1b0_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=49.6.0=py39h6e9494a_3
  - shapely=1.7.1=py39h7edaf14_1
  - sip=4.19.13=py39h23ab428_0
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.33.0=hffcf06c_0
  - terminado=0.9.4=py39hecd8cb5_0
  - testpath=0.4.4=pyhd3eb1b0_0
  - tk=8.6.10=hb0a8c7a_0
  - tornado=6.1=py39hcbf5805_1
  - traitlets=5.0.5=pyhd3eb1b0_0
  - tzdata=2020f=he74cb21_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py39hecd8cb5_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py39hecd8cb5_0
  - xz=5.2.5=h1de35cc_0
  - zeromq=4.3.4=h23ab428_0
  - zipp=3.4.1=pyhd3eb1b0_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.5=h41d2c2f_0
  - pip:
    - beamngpy==1.18
    - deap==1.3.1
    - jinja2==2.11.2
    - markupsafe==1.1.1
    - msgpack==1.0.2
    - pygame==2.0.1
    - pyopengl==3.1.5
prefix: /Users/vuong/opt/anaconda3/envs/ac3r
